image:
  file: .gitpod.Dockerfile

ports:
  # Laravel server
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore

tasks:
  - init: >
      mysql -u root -e "create database example_app" &&
      mysql -u root -p example_app < database/db_sample.sql &&
      cp .env.example .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      sed -i "s|ASSET_URL=|ASSET_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      composer install &&
      npm i &&
      php artisan key:generate
    command: >
      php -S 0.0.0.0:8000 -t public
    
